### ISSUE TITLE
Upgrade docker image

### ISSUE THREAD

**Issue by decentral1se** [codestation/drone-stack#2]
https://github.com/codestation/drone-stack/blob/082494fcce8059cd4967d110af632f9053024157/Dockerfile#L15

There is a new version (`19.03.8`). I am not sure what to say about users wanting different versions of docker on the container for deployment. For example, to support docker-compose 3.7 and so on.

Thanks for this plugin, very handy!

**Comment by codestation** [comment]
I don't use the plugin anymore (prefer to use plugins/webhook to send a signal to codestation/swarm-updater) but i updated the project and image so this doesn't rot.
